version: '3.8'
services:
  order:
    restart: always
    container_name: "order"
    image: orderapplication
    build: ./ml-order
    ports:
      - "8080:8080"
    depends_on:
      - mysql_db
      - mongo_db
      - rabbitmq
    links:
      - mysql_db
      - mongo_db
      - rabbitmq
    environment:
      DATASOURCE_URL: jdbc:mysql://mysql_db:3306/ibiza?createDatabaseIfNotExist=true&useSSL=false&useTimezone=true&serverTimezone=UTC
      DATASOURCE_USERNAME: root
      DATASOURCE_PASSWORD: root
      MONGO_URI: mongodb://root:root@mongo_db:27017
      MONGO_DATABASE: aruba
      SPRING_DATA_MONGODB_DATABASE: aruba
      SPRING_DATA_MONGODB_URI: mongodb://root:root@mongo_db:27017
      RABBIT_HOST: rabbitmq
      RABBIT_USERNAME: guest
      RABBIT_PASSWORD: guest
  register:
    restart: always
    container_name: "register"
    image: registerapplication
    build: ./ml-register
    ports:
      - "8081:8081"
    depends_on:
      - mysql_db
      - rabbitmq
    links:
      - mysql_db
      - rabbitmq
    environment:
      DATASOURCE_URL: jdbc:mysql://mysql_db:3306/las_vegas?createDatabaseIfNotExist=true&useSSL=false&useTimezone=true&serverTimezone=UTC
      DATASOURCE_USERNAME: root
      DATASOURCE_PASSWORD: root
      RABBIT_HOST: rabbitmq
      RABBIT_USERNAME: guest
      RABBIT_PASSWORD: guest
  mongo_db:
    container_name: "mongo_db"
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
  mysql_db:
    container_name: "mysql_db"
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "3306:3306"
  rabbitmq:
    container_name: "rabbitmq"
    image: rabbitmq:3-management
    expose:
      - "5672"
    ports:
      - "15672:15672"
      - "5672:5672"
  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - ./ml-order/configuration/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - 9090:9090
  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/grafana

volumes:
  prometheus_data:
  grafana_data: